spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team1_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be10_team1
    password: N(zwIEW9ge2O3yXO

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


toss:
  secret-key: test_sk_XZYkKL4Mrj1zeG6AOQvAV0zJwlEW
  api-key: test_ck_0RnYX2w532DyJ7OkKwqMrNeyqApQ